changelog:
  categories:
    - title: Breaking change
      labels:
        - 'sem-pr: breaking change'
    - title: Features
      labels:
        - 'sem-pr: feat'
    - title: Bug Fixes
      labels:
        - 'sem-pr: fix'
    - title: Types Changes
      labels:
        - types
    - title: Other Changes
      labels:
        - '*'
  exclude:
    authors:
      - dependabot
