name: "relabel by sem pr"
on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  relabel:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: info
        id: info
        uses: hankei6km/gha-sem-from-title@v0
        with:
          title: ${{ github.event.pull_request.title }}
      - name: edit
        uses: hankei6km/gha-sem-pr-labeler@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          pr_num: ${{ github.event.pull_request.number }}
          type: ${{ steps.info.outputs.type }}
          is_breaking_change: ${{ steps.info.outputs.is_breaking_change }}
